# MONGO DB SETTINGS FOR REPOSE PHONE HOME
# NEED TO SPECIFY THESE

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=12345
#spring.data.mongodb.username=mongo_user
#spring.data.mongodb.password=mongo_pass

#or
#spring.data.mongodb.uri=mongodb://mongo_user:mongo_pass@localhost:12345/db
